### ISSUE TITLE
Home page footer is cut off along along with console warnings/error.

### ISSUE THREAD

**Issue by Josephus-P** [Lambda-School-Labs/labs9-property-management#118]
![footer](https://user-images.githubusercontent.com/12503087/51436292-27128f80-1c50-11e9-8e3e-2877e74bdffe.png)
![errors](https://user-images.githubusercontent.com/12503087/51436294-2974e980-1c50-11e9-9345-ced9868fe96c.png)

**Comment by keegn** [comment]
Resolved in pr #181
